spring.application.name=ex25-branch

server.port=8085

# DB 연결
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=1234

# Mybatis 설정
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.yac.ex25_brunch.domain
mybatis.configuration.map-underscore-to-camel-case=true

# 쿼리를 콘솔에 찍어보자~
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# 로깅레벨을 이요해서, 쿼리를 콘솔에 찍어보자~
logging.level.com.yac.ex25_brunch.mapper=DEBUG


